services:
  postgres:
    image: postgres:12.12-alpine
    container_name: sample-postgres
    ports:
      - 5432:5432
    # if you want to persist data
    volumes:
      - ./.docker/postgres:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: simple-bank
      POSTGRES_INITDB_ARGS: "--encoding=UTF-8"
    restart: always

  mysql:
    image: mysql:8.0.23
    platform: linux/amd64
    container_name: sample-mysql
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: simple-bank
      TZ: 'Asia/Tokyo'
    volumes:
      - ./.docker/mysql/data:/var/lib/mysql
      - ./.docker/mysql/my.cnf:/etc/mysql/conf.d/my.cnf
    ports:
      - 3306:3306
